// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEpn4GAdOFeTIeeQAQ-wGKKGeB81M2-8',
    appId: '1:268873148487:web:3318c451a19c7abb516962',
    messagingSenderId: '268873148487',
    projectId: 'garagedoorbackend',
    authDomain: 'garagedoorbackend.firebaseapp.com',
    storageBucket: 'garagedoorbackend.appspot.com',
    measurementId: 'G-ZFVGPHRCWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynpVshCggXHsC74P5qm-UAqfgxs6X-Jo',
    appId: '1:268873148487:android:0f6a6ca3eb2e3c3e516962',
    messagingSenderId: '268873148487',
    projectId: 'garagedoorbackend',
    storageBucket: 'garagedoorbackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxGhW3_1XF43Ti6S50Hamu0NwDEHrckyo',
    appId: '1:268873148487:ios:60f2ca758d83a4a6516962',
    messagingSenderId: '268873148487',
    projectId: 'garagedoorbackend',
    storageBucket: 'garagedoorbackend.appspot.com',
    iosBundleId: 'com.example.smartGarageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxGhW3_1XF43Ti6S50Hamu0NwDEHrckyo',
    appId: '1:268873148487:ios:8cd70f7d0b17f5ea516962',
    messagingSenderId: '268873148487',
    projectId: 'garagedoorbackend',
    storageBucket: 'garagedoorbackend.appspot.com',
    iosBundleId: 'com.example.smartGarageApp.RunnerTests',
  );
}
